### ISSUE TITLE
Configuration for Synology CardDAV Server

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#1]
Hello :)

I would like to use a php code, which can connect to my CardDAV server (I know url, username and password), get contacts and the option to add contacts.

I guess you code can do this, but I don't know how I have to configure that :/
Can you show me a simple example?

1. Connect to Server
2. Get contacts
3. Add contact

Thank you very much !!

**Comment by mstilkerich** [comment]
Hello,

  this should be easily possible. Have you taken a look at [doc/quickstart.php](https://github.com/mstilkerich/carddavclient/blob/master/doc/quickstart.php)? It should cover all what you want to do and just requires updating the CardDAV server data at the start of the script and then can be executed. You can use it as a starting point for your own code.

A few notes for the individual steps:

## Connect to server
You can use the discovery service as shown in the quickstart script. However, the discovery will return all the addressbooks it finds on the server. If you already know the exact URL of a specific addressbook and only want to access that addressbook, you can directly create the addressbook object.

```php
// you can pass the URI of the addressbook also as discovery URI
$account = new Account('https://carddav.example.com/user/abooks/abook1', 'username', 'password');
$abook = new AddressbookCollection('https://carddav.example.com/user/abooks/abook1', $account);
```

## Get contacts
To retrieve the contacts, you can use the Sync service with an empty sync token as shown in the quickstart script. For this you need to implement the `SyncHandler` interface as also shown in the script. Your sync handler will get each addressbook object reported as a changed object on the first sync. You will get the cards as VCard objects of the sabre/vobject library. You can find documentation on how to work with them [here](https://sabre.io/vobject/vcard/).

An an alternative to using the sync service, you can query the children of the addressbook and get the cards you want yourself:

```php
$children = $abook->getChildren();
foreach ($children as $child) {
  $vcard = $abook->getCard($child->getUri());
}
```

If you are interested in all cards, the sync service will use a more efficient way of getting the cards than the above example where each card is downloaded in a separate request to the server.

## Add contact

Adding a contact is covered in the quickstart script as well. It's pretty simple:

```php
[ 'uri' => $cardUri, 'etag' => $cardETag ] = $abook->createCard($vcard);
```

The card needs to be passed as a sabre/vobject VCard object. The operation returns the URI of the newly created card and the ETag. The etag is kind of a version specifier for the VCard used by the CardDAV server. You need it when updating a card to make sure it has not changed server side in the meantime.

But if you have any specific questions or problems, I'm happy to help.

**Comment by Ghost108** [comment]
My problem is that I don't work with composer.
is there a solution available without composer ?

**Comment by mstilkerich** [comment]
You need composer to fetch the library's dependencies and for the autoloader that loads the dependencies when needed.

If you run composer one to fetch the dependencies and generate the autoloader, you can copy around the lib with the vendor directory (which contains the dependencies) and do not need composer anymore. Composer stores everything needed in the vendor directory.

**Comment by Ghost108** [comment]
1. I installed composer for Windows.
2. I created a folder C:\temp
3. There I placed your files 
4. cmd > cd C:\temp\
5. composer install --no-dev (OK)
6. composer.phar require mstilkerich/carddavclient

I get this output:

![image](https://user-images.githubusercontent.com/17011498/103541309-8b5da680-4e9b-11eb-9505-e055847cafe2.png)

**Comment by mstilkerich** [comment]
You don't have to put anything in that directory, carddavclient will also be fetched by composer and put in the vendor directory. The main directory then should contain your own application code. I don't know why you get that composer output, it looks like when calling composer without any arguments. For starters, you could copy quickstart.php to the main directory

I also tried on windows, here's what it looks like for me:

![Capture](https://user-images.githubusercontent.com/3405515/103547082-383c2180-4ea4-11eb-80dc-b2d03a85b96b.PNG)

**Comment by mstilkerich** [comment]
Are you still interested in this? Otherwise I'll close this issue in a couple of days without reply.

**Comment by Ghost108** [comment]
Sorry for the delay :/
I did the same like you and my "temp" folder looks now like this:

![image](https://user-images.githubusercontent.com/17011498/104279412-8b1c6700-54aa-11eb-925c-01f9788fe007.png)

What I have to do now ?
For exmaple: How can I now connect to my cardDAV server?

You called a file like quickstart.php ... should I put this file into the root directory?
Please help !! :)

**Comment by mstilkerich** [comment]
Hello,

  this looks as expected. Yes, place the your code or for starters quickstart.php in the main folder, adapt the data for your carddav server in the beginning of the script and run it. 

If this works, you can adapt the code in quickstart.php to do what you want, or develop your own script.

**Comment by Ghost108** [comment]
Okay ! With your quickstart.php I can now successfully:
- connect to my carddav
- create a contact

But now I would like to create a very minimized way (without discovery) to connect to my server:
I tried this:

```
<?php

require 'vendor/autoload.php';

use MStilkerich\CardDavClient\{Account, AddressbookCollection, Config};
use MStilkerich\CardDavClient\Services\{Discovery, Sync, SyncHandler};

use Psr\Log\{AbstractLogger, NullLogger, LogLevel};
use Sabre\VObject\Component\VCard;

$account = new Account('http://localhost:3333/carddav/SynoContacts/1c7da839-124s-4f92-b809-62e6f83219a3/, 'MyUsername', 'MyPassword');
$abook = new AddressbookCollection('http://localhost:3333/carddav/SynoContacts/1c7da839-124s-4f92-b809-62e6f83219a3/,', $account);

?>
```

Now the connection doesn't work.
I get this error:

> Fatal error: Uncaught TypeError: Argument 1 passed to GuzzleHttp\Middleware::log() must be an instance of Psr\Log\LoggerInterface, null given, called in /volume1/web/test/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php on line 97 and defined in /volume1/web/test/vendor/guzzlehttp/guzzle/src/Middleware.php:192 Stack trace: #0 /volume1/web/test/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php(97): GuzzleHttp\Middleware::log(NULL, Object(GuzzleHttp\MessageFormatter)) #1 /volume1/web/test/vendor/mstilkerich/carddavclient/src/CardDavClient.php(63): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->__construct('http://localhost....', 'MyUsername', 'MyPassword') #2 /volume1/web/test/vendor/mstilkerich/carddavclient/src/Account.php(101): MStilkerich\CardDavClient\CardDavClient->__construct('http://localhost....', 'MyUsername', 'MyPassword') #3 /volume1/web/test/vendor/mstilkerich/carddavclient/src/WebDavResource.php(91): MStilkerich\CardDavClient\Account->getClient('http://localhost in /volume1/web/test/vendor/guzzlehttp/guzzle/src/Middleware.php on line 192

**Comment by mstilkerich** [comment]
Before using the library you need to initialize it using Config::init() with the logger objects. If you don't pass logger objects, you won't get any log output. See quickstart for example.

**Comment by Ghost108** [comment]
Perfect ! That works ! 
I modified your code a "little bit" to get all contacts in array:

```
$children = $abook->getChildren();
foreach ($children as $child) {
  $vcard**[]** = $abook->getCard($child->getUri());
}

echo '<pre>';
var_dump($vcard);
echo '</pre>';
```

Is there an way to only the email addresses of a contact instead of all details?

**Comment by mstilkerich** [comment]
Sure, $vcard->EMAIL can be iterated. For details on how to work with vcards see https://sabre.io/vobject/vcard/

**Comment by Ghost108** [comment]
Good morning :)


I tried this:

```
$children = $abook->getChildren();
foreach ($children as $child) {
  $vcard = $abook->getCard($child->getUri());
  echo $vcard->EMAIL;
}
```

result:
**Notice: Trying to get property 'EMAIL' of non-object in /volume1/web/test/quickstart.php on line 33**

**Comment by Ghost108** [comment]
I can solve this "problem" like this:

```
$children = $abook->getChildren();
foreach ($children as $child) {
  $vcard = $abook->getCard($child->getUri());
  echo $vcard["vcard"]->EMAIL->getvalue();
}
```

I would like to check if a mail address can found in my contacts.

Is there a a option to query a specifiy contact instead of all?
Like: Show me the contact where email = "mail@domain.de" 

otherwise I will check each contact with if and else.

**Comment by mstilkerich** [comment]
Searching the addressbook server-side is currently not supported, but I intend to add this when I find time (#2). For know, you will have to check all the cards.

For ssl to work you need a valid server certificate with a CA certificate in the certificate store of the client. For localhost you don't need an SSL certificate and you won't get one from an official CA.

**Comment by Ghost108** [comment]
I have to use ssl. Is there a way to ignoriert the invalid certificate

**Comment by mstilkerich** [comment]
If you want to use SSL you have to set it up properly. You can get a free certificate from lets encrypt. I believe synology has support for letsencrypt. You could also create a self signed certificate and import your CA into the trusted CA store of the client. There is no option to disable certificate verification in carddavclient.

**Comment by Ghost108** [comment]
Okay ! Last question:
Howe can I check that the connection to carddav server was successfull?

something like:

if Connection == ok {
do something
}

**Comment by mstilkerich** [comment]
Generally, the lib throws Exceptions when something goes wrong that it cannot handle. The exception comes with an error message. So you should wrap the use of the library in a try / catch block.

No connection is established when you construct the object. The connection is established with the first operation that requires sending a request to the carddav server.

**Comment by Ghost108** [comment]
Thank you very much !
Thanks for the time you've spend for me !
You made my day !

**Comment by mstilkerich** [comment]
Thanks, you're welcome :-)
