### ISSUE TITLE
Query specific vcard

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#10]
Hi ! :)

I updated to version 1.1.0
Is there now a code part available to query a contact like ?:

Get Contact where email == mail@domain.de

**Comment by mstilkerich** [comment]
Hello, yes that is now possible using the `query()` API of an `AddressbookCollection` object. Please see the API docs on usage, specifically the available search filters.

**Comment by Ghost108** [comment]
I tried this:

```
$account = new Account(URL, USERNAME, PASSWORD);
$abook = new AddressbookCollection(URL, $account);

$contacts = $abook->query(
     ['EMAIL' => 'test@mail.de']
);           
	
var_dump($contacts);
```

Output:

`Fatal error: Uncaught InvalidArgumentException: Not a valid match specifier for TextMatch: test@mail.de in /volume1/web/test/vendor/mstilkerich/carddavclient/src/XmlElements/TextMatch.php:133 Stack trace: #0 /volume1/web/test/vendor/mstilkerich/carddavclient/src/XmlElements/PropFilter.php(132): MStilkerich\CardDavClient\XmlElements\TextMatch->__construct('test@mail.de') #1 /volume1/web/test/vendor/mstilkerich/carddavclient/src/XmlElements/Filter.php(131): MStilkerich\CardDavClient\XmlElements\PropFilter->__construct('EMAIL', Array) #2 /volume1/web/test/vendor/mstilkerich/carddavclient/src/AddressbookCollection.php(311): MStilkerich\CardDavClient\XmlElements\Filter->__construct(Array, false) #3 /volume1/web/test/getContactData.php(33): MStilkerich\CardDavClient\AddressbookCollection->query(Array) #4 {main} thrown in /volume1/web/test/vendor/mstilkerich/carddavclient/src/XmlElements/TextMatch.php on line 133`

**Comment by Ghost108** [comment]
I tried this:

```
$contacts = $abook->query(
     ['EMAIL' => '/de/$'],
     ['EMAIL'],
     false,
     1
);                                                        
          
echo count($contacts);
}
```

Output will shown "530" vcard results, but I set $limit to 1, correct ?
This will take 11 seconds. Not very fast :/

**Comment by mstilkerich** [comment]
Hello,
if your search results in a lot of results, these need to be transferred and thus it may take a while, depending on the connection speed with the server.

Your options ask the server to only return a single result, but unfortunately not all servers support this feature. The same for the option that asks the server to only return the EMAIL property, which would also result in less data being transferred but is also not supportrd by all servers. If your server returns more than one result, it does not support result limit. I have spent a great amount of time in documenting my experiences as to what features and bugs each server has, please see https://github.com/mstilkerich/carddavclient/blob/master/doc/QUIRKS.md

In most use cases, you should have filter criteria that result only in few matches, in those cases query should be fast even if your server returns all results.

**Comment by Ghost108** [comment]
I am using the Synology Contacts App - that's the problem with the limit :(

**Comment by mstilkerich** [comment]
Yep, radicale does not support limit or partial card retrieval. There is nothing I can do about it, you could file a feature request with radicale.
