### ISSUE TITLE
get name of person (FN)

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#11]
Hello :)

I used this code:

`$contacts = $abook->query(
	['EMAIL' => '/email@mail.de/'],
	['FN'],
	FALSE,
	1
);`

How can I get the value of  FN from this query?

**Comment by mstilkerich** [comment]
Query returns an array of VCard objects. You can access the VCard properties like properties of the object:

```php
foreach ($contacts as $card) {
    echo $card->FN;
}
```

Btw your query matches on any email address that contains email@mail.de, for example also foo.email@mail.de

If you want an exact match, you need to add the = modifier, see the docs on TextMatch class.

**Comment by Ghost108** [comment]
thanks for the hint with the "=" modifier - I fixed it !

But your code part doesn't work form me.
the "echo" will be empty

**Comment by mstilkerich** [comment]
Yeah my codd example is wrong. Please see what query() actually returns:

https://mstilkerich.github.io/carddavclient/classes/MStilkerich-CardDavClient-AddressbookCollection.html#method_query

**Comment by Ghost108** [comment]
Okay ... nur I dont know how I can handel this :/

**Comment by mstilkerich** [comment]
```php
foreach ($contacts as $contact) {
    $card = $contact["vcard"];
    echo $card->FN;
}
```
