### ISSUE TITLE
change values of an existing vcard

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#13]
Hello :)

Can you show me please, how I can change values of an existing vcard?
I know the uid of this card and would like to change (for example), the mail address.

Thank you very much :)

**Comment by mstilkerich** [comment]
Hello,

  this is an issue tracker, not a support forum. This library comes with extensive API documentation, which describes the possibilities of how to retrieve vcards and write them back.

How to modify the vcard can be found in the sabre/vobject documentation.
https://sabre.io/vobject/vcard/

Sorry I have to rtfm you here, but if you want to develop software you should be able to familiarize yourself with the used libraries by reading their documentation.

**Comment by Ghost108** [comment]
thank you for the documentation :)
