### ISSUE TITLE
Add multiple phone numbers

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#16]
Hi !

I can add a new vcard like this:

`		$vcard =  new VCard([
			'VERSION'	=> '3.0',
			'FN'				=> $_POST['salutation'].' '.$_POST['fname'].' '.$_POST['lname'],
			'N' 				=> [$_POST['lname'], $_POST['fname'], '', $_POST['salutation'], ''],
			'ORG'			=> $_POST['organization'],
			'EMAIL' 		=> $_POST['email'],
			'TEL'			=> $_POST['phone'],
			'ADR'   		=> ['', '', $_POST['address'], $_POST['city'], '', $_POST['zip'], '']
			]); `

But now I would like to add a new vcard with multiple phone numbers.
My scripts get an array like this:

`$phoneNumbers = array("number_1", "number_2", ...)`

How can I add multiple phone numbers?
Thanks !

**Comment by mstilkerich** [comment]
You can use the `$vcard->add()` method. Please read https://sabre.io/vobject/vcard/
