### ISSUE TITLE
PHP Warning:  Use of undefined constant CURLAUTH_NEGOTIATE

### ISSUE THREAD

**Issue by n0rvik** [mstilkerich/carddavclient#17]
OS: `CentOS 7`

PHP:
```
# php -v
PHP 7.4.27 (cli) (built: Dec 14 2021 17:17:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

```
RoundCube: 1.5.2

Warning:

```
PHP Warning:  Use of undefined constant CURLAUTH_NEGOTIATE - assumed 'CURLAUTH_NEGOTIATE' (this will throw an Error in a future version of PHP) in /usr/share/roundcubemail-1.5.2/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php on line 106
```

**Comment by mstilkerich** [comment]
Hello,

  `CURLAUTH_NEGOTIATE` is available from PHP 7.0.7 and curl version 7.38.0 (released 9/2014) ([see here](https://www.php.net/manual/en/curl.constants.php)). It replaces the now deprecated constant `CURLAUTH_GSSNEGOTIATE`, which appears to be still included in the most recent php and curl versions.

Cent OS 7 comes with a very old curl 7.29.0 (released 2/2013).

I don't intend to implement a workaround to support these ancient curl versions. I can suggest the following simple local fix for you: You can simply replace `CURLAUTH_NEGOTIATE` with its previous name `CURLAUTH_GSSNEGOTIATE`, which is known to the older curl version. This actually fixes the issue, so even kerberos authentication should work fine. If you ever upgrade to a newer version of carddavclient, you would have to repeat this step as your change would be overwritten.

 You can ignore the issue if you don't use kerberos authentication and are not annoyed by the log entries. Assuming you will upgrade your system at some point, the warning will vanish with a newer version of curl.
