### ISSUE TITLE
HTTPS verify

### ISSUE THREAD

**Issue by Gezzo42** [mstilkerich/carddavclient#22]
Hello,
I use the library with Windows and had the problem, that my local server has no valid certificat (self signed). I added `$guzzleOptions['verify'] = false;` to `prepareGuzzleOptions()` in `HttpClientAdapterGuzzle.php`. Is there a better variant? Otherwise I would suggest, that this option can be given to `Config::init()`. Or did I miss something?
Thanks for the help and the library!
Gezzo

**Comment by mstilkerich** [comment]
Hi,

  the proper way to do it would to add an option to the `$options` parameter of `Config::init()`.

However, I wonder why it is not possible for you to set up SSL trust properly. If it's a public domain, there are providers like lets encrypt that issue free certificates that are trusted by current browsers / operating systems. If its a closed environment with a private CA, you can import that CA's certificate as a trusted CA in the client computers. When disabling certificate validation, I wonder why use SSL in the first place?

**Comment by Gezzo42** [comment]
Hi,
thanks for your quick response. It's part of a private network and I like the possibility of encryption. If this option is provide, I should be possible to also set the certificates path. I'm also not sure, which CAs curl is using.

**Comment by mstilkerich** [comment]
Hello,

I agree we can add an option like the [verify option in guzzle](https://docs.guzzlephp.org/en/stable/request-options.html#verify) to the options array passed to `Config::init()`. However, that will mean that the setting is applied library wide, i.e. when talking to different servers this setting will also take effect.

Per server settings are currently available only in form of the credentials given to the `Account` class, and passed along to the HTTP client adapter. Without larger changes, a `verify` setting could additionally be given in the credentials array when creating an account, as to enable per-account configuration of SSL certificate verification. It's not really nice, but still somewhat related to authentication so I wouldn't mind too much.

Anyway, I won't have time in the near future to implement this. If you want, you can try yourself and submit a pull request.
