### ISSUE TITLE
Requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by IamSAB** [mstilkerich/carddavclient#23]
I cannot install the client for Laravel 9. It seems its just because of the PSR stuff.

```
Problem 1
    - mstilkerich/carddavclient[v1.2.0, ..., 1.2.x-dev] require psr/log ^1.1 -> found psr/log[1.1.0, ..., 1.1.4] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires mstilkerich/carddavclient ^1.2 -> satisfiable by mstilkerich/carddavclient[v1.2.0, ..., 1.2.x-dev].
```

Will the client also work with more recent dependecies?

**Comment by mstilkerich** [comment]
Hello,

 yes, all psr/log versions should actually work. I have to make some small adjustments to the tests since there is a (dev-only) dependency that will also tie psr/log to a v1 version, but I can do without it.
