### ISSUE TITLE
Connect to Google Contacts not working

### ISSUE THREAD

**Issue by radabo** [mstilkerich/carddavclient#24]
I have been receiving a message since yesterday:

Exception while querying current-user-principal: Expected Multistatus HTTP request was not successful (403 Forbidden): { "error": { "code": 403, "message": "The request is missing a valid API key.", "status": "PERMISSION_DENIED" } } Exception while querying current-user-principal: Expected Multistatus HTTP request was not successful (404 Not Found):

I regenerated password for 2FA, but access still not working :(

const DISCOVERY_URI = "google.com";

thank you for help 💯

**Comment by mstilkerich** [comment]
It appears Google have finally disabled basic authentication for the CardDAV. They have announced it long ago, but so far basic authentication remained available. Now it is not accepted anymore. There is nothing I can do about it.

https://developers.google.com/people/carddav#google’s_carddav_requires_oauth_20

OAuth2 authentication still works fine with carddavclient.

**Comment by mstilkerich** [comment]
Looks like Google fixed it, Basic auth works again (without API key).
