### ISSUE TITLE
BDAY property no longer synced from Nextcloud to Android

### ISSUE THREAD

**Issue by fwiep** [mstilkerich/carddavclient#26]
Hello,

Have been using `carddavclient` v1.4.0 for quite some time without issues in a custom built PHP address book. Since about a month, synchronizing from my app to a Nextcloud 27 instance works, but birthdays no longer get synced from that Nextcloud to several Android devices. At first, I though it was an issue with the Android synchronization using DAVx5 and filed [an issue with them](https://github.com/bitfireAT/davx5-ose/discussions/385).

Now, it turns out, that the format of the `BDAY` vCard property is causing this particular issue. Apparently, if the property is formatted like this,
```
BDAY:19510311T000000+0100
```
the issue is present. However, when the property is formatted like this,
```
BDAY;VALUE=DATE:19510311
```
all is well and the birthdays get synchronized to the Android devices.

I've tracked the formatting down to the following file in one of this project's dependencies: `vendor/sabre/vobject/lib/Property/VCard/DateAndOrTime.php`.

How can I solve this issue? Should `carddavclient` be updated, or the `Sabre\VObject` library it depends upon?

Thank you very much, kind regards,
FWieP

**Comment by mstilkerich** [comment]
Hello,

  do you create a version 3 or version 4 vcard? The property definitions may vary depending on the VCard version, but Sabre should take care to use a format suited for the chosen version (if the input is understood correctly). Nextcloud very likely also uses sabre/vobject on the receiving end, at least sabre/vobject is bundled with nextcloud.

So lets take a look.

### VCard Version 3

The definition of the BDAY property in VCard 3 ([1]) specifies it can be either a single date or a single date-time value. The value produced by sabre includes a time, so lets look at how date-time is defined in MIME-DIR [3]. The definition for date-time further refers to ISO 8601 format [4]. The _Examples for "date-time"_ include 19960811T123456Z, which is the format also used in your example. If you have a timezone other than UTC (thats what the Z in the end stands for), it would be represented by the timezone offset +HH:MM or -HH:MM.

### VCard Version 4

The VCard4 definition [2] of the BDAY property allows it to have a single date-and-or-time value [5], or even a text value (the example given is `text:circa 1800`). So VCard4 is very liberal about the allowed values and also would allow a time without a date. But lets forget about this and focus on date and date-time.

The definition of date-time [6] in VCard4 like VCard3 refers to ISO 8601 [4].

The value can also be provided as a `VALUE` parameter like you have in your second example (albeit not as a URI as in your example). The examples following the BDAY property definition in [2] include `BDAY;19531015T231000Z`. It is the same format as above.

### Conclusion
So to conclude, there are several valid formats a BDAY property value can take, and they may include a time in addition to the date. So the addressbook application processing the vcard should be able to interpret the above timestamp. I don't see an error in vobject here (carddavclient itself does not touch the vcard properties).

In fact, I cannot find reference that your second example that specifies the date value as a URI (with the `DATE:` prefix) is permissible per the spec, but I might have missed something here.

### Sidenote

I did not check the vobject code, but I did a short test where I could not see vobject changing the format of the BDAY property.

```php
<?php

require 'vendor/autoload.php';

use Sabre\VObject\Component\VCard;

$vcard = new VCard([
    'VERSION' => '3.0',
    'FN'  => 'Cowboy Henk',
    'N'   => ['Henk', 'Cowboy', '', 'Dr.', 'MD'],
    'BDAY' => '19510311',
]);

echo $vcard->serialize();
```

This outputs:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.5.3//EN
UID:sabre-vobject-f4c2ef50-bba4-4499-bc48-3e61fc29a49c
FN:Cowboy Henk
N:Henk;Cowboy;;Dr.;MD
BDAY:19510311
END:VCARD
```

So I wonder about the input / the source vcard that is passed to vobject.

### References
[1] [BDAY VCard3](https://www.ietf.org/rfc/rfc2426.html#section-3.1.5)
[2] [BDAY VCard4](https://www.ietf.org/rfc/rfc6350.html#section-6.2.5)
[3] [MIME DIR date-time definition](https://www.ietf.org/rfc/rfc2425.html#section-5.8.4)
[4] [ISO 8601 date and time formats](https://en.wikipedia.org/wiki/ISO_8601)
[5] [VCard4 date-and-or-time definition](https://www.ietf.org/rfc/rfc6350.html#section-4.3.4)
[6] [VCard4 date-time definition](https://www.ietf.org/rfc/rfc6350.html#section-4.3.3)

**Comment by fwiep** [comment]
Hello again,

Thank you very much for this in-depth explanation. It seems this issue is not as easily fixed as I'd hoped. 

I use VCard v4, and `Sabre\VObject` indeed does convert PHP's `\DateTime` into a `'Ymd\\THisO'` formatted string. This is all well within the ISO's specs. `carddavclient` and even `Sabre\VObject` are not to be blamed for this.

So, my question becomes: where should I go to fix this issue?
- With the Nextcloud developers? They seem to have tackled the different `BDAY` formats, but prefer `BDAY;VALUE=DATE:Ymd`. 
- Or with the DAVx5 developers? They seem to ignore the plain `BDAY:Ymd\\THisO` format all together.

I'll try my luck with the latter.

Thanks, kind regards,
FWieP
