### ISSUE TITLE
SyncHandler not receiving vcf

### ISSUE THREAD

**Issue by IamSAB** [mstilkerich/carddavclient#28]
I use the PRODID property of the vcard to guess the origin of their creation. However, the SyncHanlder receives only VCards which receive a new PRODID on creation in your Sync class.

Therefore, I would like to have access to the original VCF in the SyncHandler. That is currently not possible.
It would be if we change the SyncHandler interface on line 44 to
`public function addressObjectChanged(string $uri, string $etag, ?VCard $card, ?string $vcf): void;`
and the Sync method synchronizeOneBatch on line 162 to
`$handler->addressObjectChanged($obj["uri"], $obj["etag"], $obj["vcard"] ?? null, $obj['vcf'] ?? null);`.

That way I could receive the fetched vcf within my SyncHandler which extends the interface.
Or is there a reason, why the vcf is not passed to the SyncHandler?

**Comment by mstilkerich** [comment]
Hi, 

- The library (nor sabre/vobject used to parse the vcards) does **not** alter the PRODID property. You can access the PRODID via the vcard `$card->PRODID`.
- There should be no need to provide the RAW vcard text. The interface to the application side of the library uses Sabre VObject for vcards. Passing the string would be redundant. You can get the string back using `$card->serialize()`

**Comment by IamSAB** [comment]
Ok, thanks for the update, then I check again.
Because the prodid was the one of sabre after sync, even when the same card on the server-side had another one. I concluded, that vobject sets its own prodid after parsing because later in case you would save it, it has the correct prodid.

**Comment by IamSAB** [comment]
Hey, i ran some test and i am bit confused:

```php
<?php

use MStilkerich\CardDavClient\Account;
use MStilkerich\CardDavClient\AddressbookCollection;
use MStilkerich\CardDavClient\Config;
use MStilkerich\CardDavClient\Services\Sync;
use MStilkerich\CardDavClient\Services\SyncHandler;
use Sabre\VObject\Component\VCard;

require 'vendor/autoload.php';

$pw = "<pw>";
$host = "<host>";
$user = "<user>";
$bookUid = "<book-uid>";

$baseUri = "$host/addressbooks/$user/";
$bookUri = $baseUri . "$bookUid/";

$book = new AddressbookCollection($bookUri, new Account($baseUri, [
  'username' => $user,
  'password' => $pw
]));

Config::init();

class EchoSyncHandler implements SyncHandler
{
  public function addressObjectChanged(string $uri, string $etag, ?VCard $card): void
  {
    if (isset($card)) {
      echo $card->PRODID ?? "<no prodid>";
      echo "\n";
      echo $card->UID ?? "<no uid>";
      echo "\n\n---\n\n";
    }
  }

  public function addressObjectDeleted(string $uri): void
  {
  }

  public function getExistingVCardETags(): array
  {
    return [];
  }

  public function finalizeSync(): void
  {
  }
}

$peterUid = '12f11d33-d290-4736-821e-7638ab48db4a';

$book->createCard(new VCard([
  'UID' => $peterUid,
  'N' => ['', 'Peter'],
  'PRODID' => 'Client 1'
]));

$book->createCard(new VCard([
  'UID' => 'dd553477-ae70-4c76-a6d3-dcc1dd9eea60',
  'N' => ['', 'Arthur'],
  'PRODID' => 'Client 2'
]));

$book->createCard(new VCard([
  'UID' => 'c3be592e-4807-4723-82f2-492ae1aa16d8',
  'N' => ['', 'Jonathan'],
  'PRODID' => 'Client 2'
]));

$sync = new Sync;

$sync->synchronize($book, new EchoSyncHandler);

list('vcard' => $vcard, 'vcf' => $vcf) = $book->getCard($bookUri . "/$peterUid.vcf");

echo "\n";
echo (string) $vcard->N->getParts()[1];
echo "\n";
echo $vcard->PRODID;
echo "\n";
echo $vcf;
echo "---";
```

my output from this script is
```-//Sabre//Sabre VObject 4.5.3//EN
12f11d33-d290-4736-821e-7638ab48db4a

---

-//Sabre//Sabre VObject 4.5.3//EN
dd553477-ae70-4c76-a6d3-dcc1dd9eea60

---

-//Sabre//Sabre VObject 4.5.3//EN
c3be592e-4807-4723-82f2-492ae1aa16d8

---


Peter
-//Sabre//Sabre VObject 4.5.3//EN
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.5.3//EN
UID:12f11d33-d290-4736-821e-7638ab48db4a
N:;Peter;;;
FN:Peter 
END:VCARD
```
what makes no sense to me. Can you also test and confirm?

**Comment by mstilkerich** [comment]
Hello,

  I would suggest you use a logger to inspect the http traffic, then you will see what is going on.

```php
class StdoutLogger extends AbstractLogger
{
    public function log($level, $message, array $context = array()): void
    {
        $ctx = empty($context) ? "" : json_encode($context);
        echo $message . $ctx . "\n";
    }
}

$log = new StdoutLogger();
Config::init($log, $log);
```

You will see with Baïkal, which, given the URL in your script, I assume you use:

```
NULL
Using auth scheme digest
"PUT /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-789032613.vcf HTTP/1.1" 201
>>>>>>>>
PUT /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-789032613.vcf HTTP/1.1
Content-Length: 120
User-Agent: GuzzleHttp/7
Host: baikal.localdomain
Content-Type: text/vcard
If-None-Match: *

BEGIN:VCARD
VERSION:4.0
PRODID:Client 1
UID:12f11d33-d290-4736-821e-7638ab48db4b
N:;Peter;;;
FN:Peter
END:VCARD

<<<<<<<<
HTTP/1.1 201 Created
Date: Sat, 09 Mar 2024 19:04:44 GMT
Server: Apache/2.4.57 (Debian)
X-Powered-By: PHP/8.1.27
Set-Cookie: PHPSESSID=dce2de87749d50b018c59835b33b160e; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Sabre-Version: 4.5.0
Content-Length: 0
ETag: "784d3160f328dfff5f621285a7a8534b"
Content-Type: text/html; charset=UTF-8


--------
NULL
Using auth scheme digest
"GET /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-789032613.vcf HTTP/1.1" 200
>>>>>>>>
GET /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-789032613.vcf HTTP/1.1
User-Agent: GuzzleHttp/7
Host: baikal.localdomain


<<<<<<<<
HTTP/1.1 200 OK
Date: Sat, 09 Mar 2024 19:04:44 GMT
Server: Apache/2.4.57 (Debian)
X-Powered-By: PHP/8.1.27
Set-Cookie: PHPSESSID=b6a9a6366cb9a542783e7ac5c0a2157a; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Sabre-Version: 4.5.0
Last-Modified: Sat, 09 Mar 2024 19:04:44 GMT
ETag: "784d3160f328dfff5f621285a7a8534b"
Content-Length: 145
Content-Type: text/vcard; charset=utf-8

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.5.4//EN
UID:12f11d33-d290-4736-821e-7638ab48db4b
N:;Peter;;;
FN:Peter
END:VCARD

--------
NULL
```

So as you can see in the HTTP traffic, carddavclient uploads the card with the PRODID you set, but it comes back from the server with a different PRODID. If you look closely, you will see that the card provided by the server also indicates VERSION 3.0. What happend? Baïkal converted the card to V3, and because it modified the card it also updated the PRODID.

Now try with uploading a v3 vcard:
```php
$card = new VCard([
  'VERSION' => '3.0',
  'UID' => $peterUid,
  'N' => ['', 'Peter'],
  'PRODID' => 'Client 1'
]);
```

And you see the PRODID is not modified:
```
NULL
Using auth scheme digest
"PUT /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-2141556693.vcf HTTP/1.1" 201
>>>>>>>>
PUT /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-2141556693.vcf HTTP/1.1
Content-Length: 120
User-Agent: GuzzleHttp/7
Host: baikal.localdomain
Content-Type: text/vcard
If-None-Match: *

BEGIN:VCARD
VERSION:3.0
PRODID:Client 1
UID:12f11d33-d290-4736-821e-7638ab48db4b
N:;Peter;;;
FN:Peter
END:VCARD

<<<<<<<<
HTTP/1.1 201 Created
Date: Sat, 09 Mar 2024 19:02:28 GMT
Server: Apache/2.4.57 (Debian)
X-Powered-By: PHP/8.1.27
Set-Cookie: PHPSESSID=667e411672a2a037eaa0158cad237963; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Sabre-Version: 4.5.0
Content-Length: 0
ETag: "2f9650a205ce083ba62066b23d4cfdbb"
Content-Type: text/html; charset=UTF-8


--------
NULL
Using auth scheme digest
"GET /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-2141556693.vcf HTTP/1.1" 200
>>>>>>>>
GET /dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-2141556693.vcf HTTP/1.1
User-Agent: GuzzleHttp/7
Host: baikal.localdomain

<<<<<<<<
HTTP/1.1 200 OK
Date: Sat, 09 Mar 2024 19:02:28 GMT
Server: Apache/2.4.57 (Debian)
X-Powered-By: PHP/8.1.27
Set-Cookie: PHPSESSID=f0bd063f1776f903013a514d5e0e53c0; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
X-Sabre-Version: 4.5.0
Last-Modified: Sat, 09 Mar 2024 19:02:28 GMT
ETag: "2f9650a205ce083ba62066b23d4cfdbb"
Content-Length: 120
Content-Type: text/vcard; charset=utf-8

BEGIN:VCARD
VERSION:3.0
PRODID:Client 1
UID:12f11d33-d290-4736-821e-7638ab48db4b
N:;Peter;;;
FN:Peter
END:VCARD

--------
NULL
```

**Comment by mstilkerich** [comment]
Doing a bit further testing with curl, it looks like the server stores the original v4 vcard. But carddavclient does not ask for a specific vcard version, and I guess since vcard v3 is the must-support version for CardDAV servers (RFC 6352) Baikal converts to v3.

```
curl -H "Accept: text/vcard; version=4.0" --digest -u mikey 'http://baikal.localdomain/dav.php/addressbooks/mikey/default/12f11d33-d290-4736-821e-7638ab48db4b-789032613.vcf'
Enter host password for user 'mikey':
BEGIN:VCARD
VERSION:4.0
PRODID:Client 1
UID:12f11d33-d290-4736-821e-7638ab48db4b
N:;Peter;;;
FN:Peter
END:VCARD
```

**Comment by mstilkerich** [comment]
And here is where the magic happens:

https://github.com/sabre-io/dav/blob/da8c1f226f1c053849540a189262274ef6809d1c/lib/CardDAV/Plugin.php#L729
https://github.com/sabre-io/dav/blob/da8c1f226f1c053849540a189262274ef6809d1c/lib/CardDAV/Plugin.php#L756
https://github.com/sabre-io/http/blob/7aef10aa72448d5733978e9d6a0613ee6fde13c4/lib/functions.php#L104

Sabre/DAV always converts the VCard to a "negotiated" format. If nothing is explicitly requested, it defaults to V3.

**Comment by IamSAB** [comment]
Thank you for your research.
I use a swiss hoster called infomaniak, but they also use sabre for their workspace.
I'd like to confirm your findings with my hoster.

However, using your http logger gives me a fatal error:
```PHP Fatal error:  Uncaught TypeError: GuzzleHttp\Middleware::log(): Argument #1 ($logger) must be of type Psr\Log\LoggerInterface, null given, called in /home/sab/Schreibtisch/carddav-test/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php on line 135 and defined in /home/sab/Schreibtisch/carddav-test/vendor/guzzlehttp/guzzle/src/Middleware.php:198
Stack trace:
#0 /home/sab/Schreibtisch/carddav-test/vendor/mstilkerich/carddavclient/src/HttpClientAdapterGuzzle.php(135): GuzzleHttp\Middleware::log()
#1 /home/sab/Schreibtisch/carddav-test/vendor/mstilkerich/carddavclient/src/CardDavClient.php(58): MStilkerich\CardDavClient\HttpClientAdapterGuzzle->__construct()
#2 /home/sab/Schreibtisch/carddav-test/vendor/mstilkerich/carddavclient/src/Account.php(163): MStilkerich\CardDavClient\CardDavClient->__construct()
#3 /home/sab/Schreibtisch/carddav-test/vendor/mstilkerich/carddavclient/src/WebDavResource.php(111): MStilkerich\CardDavClient\Account->getClient()
#4 /home/sab/Schreibtisch/carddav-test/index.php(22): MStilkerich\CardDavClient\WebDavResource->__construct()
#5 {main}
  thrown in /home/sab/Schreibtisch/carddav-test/vendor/guzzlehttp/guzzle/src/Middleware.php on line 198
```

In addition, I have to use
`abstract public function log($level, string|\Stringable $message, array $context = []): void;`
for the logger.

Composer requires probably a newer logger interface, as my composer.json is only:
```json
{
    "require": {
        "mstilkerich/carddavclient": "^1.4"
    }
}
```

**Comment by IamSAB** [comment]
And is there a way to explicitely request version 4.0 using your carddav client?

**Comment by mstilkerich** [comment]
You have to run Config::init() before using anything else from the library. Had to fix this to make your script running too. I.e. you must do init before creating the AddressbookCollection object.

There is no way to ask the server for specific vcard version with carddavclient. Carddavclient/sabre vobject can deal with any vcard version, so the idea is the server can provide whichever format it prefers (so far I would have expected the original format of the vcard). It would not solve your issue though, since you can store vcards in different versions on the server, as you have seen I stored both v3 and v4 on the same server. If you now asked for v4, v3 cards would be converted by Sabre.

Also I think you should not have an expectation that the Prodid is not changed. CardDAV servers are allowed to do changes to the cards, and should rightly indicate so by adapting the prodid. Google is an extreme example where much even user visible parts such as email type parameters are modified. I believe this is because Google contacts uses a different storage format internally and has to convert back and forth to vcard when using their carddav api.

**Comment by IamSAB** [comment]
Ok, thanks a lot for clarifying. A least I understand know what's behind my issue and how the prodid is handled by servers.
You can consider this issue as resolved, as it is not related to your client.
Thanks again!
