### ISSUE TITLE
Check if user has no mail address

### ISSUE THREAD

**Issue by Ghost108** [mstilkerich/carddavclient#3]
Good morning, 

me again (shame on me).

I check with this code if a contact has a specific mail address:

```
foreach ($contacts as $contact) {
   $vcard = $abook->getCard($contact->getUri());
   
   if ($vcard["vcard"]->EMAIL->getvalue() == "mail@domain.com") {
      echo "Mail exist!";
      exit();
   } else {
      echo "No";
}
```

Problem:
If a contact has no mail address I get this error:

> Notice: Undefined index: EMAIL; Fatal error: Uncaught Error: Call to a member function getvalue() on null

How can I handle this?

**Comment by mstilkerich** [comment]
A VCard can have no EMAIL property, but it may also have multiple EMAIL properties. Your code should be able to deal with these situations, it currently assumes that each card as one EMAIL property (only).

Something like:
```php
if (isset($vcard->EMAIL)) {
    foreach($vcard->EMAIL as $email) {
        echo "Email: $email\n";
    }
}
```

**Comment by Ghost108** [comment]
Thank you very much AGAIN 👍
