### ISSUE TITLE
Does it work without having a specific user ?

### ISSUE THREAD

**Issue by glennpierce** [mstilkerich/carddavclient#30]
Basically I am trying to create a php server that simply provides one addressbook and for that address book provide all the contacts.
It's so I and get a shared addressbook for a number of email accounts but the platform we are stuck on does not allow any carddav servers I only have php to work with. 
So I trying to do the most simple server possible ie readonly can addressbook contacts with no auth to start

I am trying to debug the server with your client but get 

Exception while querying current-user-principal: Expected Multistatus HTTP request was not successful (200 OK)

I woundered it it needs a user 

my server code is poor so was debugging against a client one issue at a time :)

server code 

[carddav.php](https://pastebin.com/5Re909kC)
[member_addressbook.php](https://pastebin.com/TQK24Nvs)

I guessing the code in the client can't be used to do this kind of simple server ? 
As you can tell I am suggling with the carddav protocol.

Thanks

**Comment by mstilkerich** [comment]
Hello,

 I guess you are using Discovery, but this will require a principal URI on the server. If you create an AddressbookCollection object using the known URI of the addressbook directly, this should not be needed.

Btw, why not use Sabre/DAV or Baïkal respectively, which is a widely spread open source CardDAV/CalDav server implementation in PHP?

**Comment by glennpierce** [comment]
Thanks. I just today found out I could use the Sabre example carddav server and it seems to work with Thunderbird bookdav.

Unfortunately the roundcube clients I need it for don't seem to retrieve any entries although they are there. It also spits errors when adding although they do seem to go in. I assume roundcube bugs  and i have no control updating it .

Thanks anyway.

**Comment by mstilkerich** [comment]
Do you use rcmcarddav plugin in the roundcube clients or did you implement something yourself?

https://github.com/mstilkerich/rcmcarddav

Rcmcarddav works fine with sabre-based servers.

**Comment by glennpierce** [comment]
I using Roundcube and the plugin that were preinstalled in cpanel / tsoHost

Roundcube Webmail 1.6.0

Installed plugin
carddav	v4.4.4	[GPL-2.0](http://www.gnu.org/licenses/gpl-2.0.html)	[Download (https://github.com/mstilkerich/rcmcarddav/)

In Thunderbird / cardbook I put in the url
http://mysite.co.uk/carddav/carddav.php

And it all works fine.
I noticed that after looking back in the properties I see
http://staustellbayarchers.co.uk/carddav/carddav.php/addressbooks/admin/default/  has been configured.


In round cube I tried both urls with the same results. I get connection success and when I go to contacts it says synchronised to 0 seconds and I see no entries. Can't find any errors. 

Thanks

**Comment by mstilkerich** [comment]
You can see whats going wrong by enabling HTTP debug logging in the rcmcarddav plugin.
To do that, set
```php
$prefs['_GLOBAL']['loglevel_http'] = \Psr\Log\LogLevel::DEBUG;
```
in `roundcube/plugins/carddav/config.inc.php`.

Then take a look at the `carddav_http.log` file after attempting an addressbook synchronization via the user interface.

Also I would suggest to use the latest rcmcarddav version, I do not support v4 anymore.

**Comment by glennpierce** [comment]
Thanks for the help. Unfortunately they don't even give read permissions for roundcube/plugins/carddav/config.inc.php
Thanks for the help though.

**Comment by glennpierce** [comment]
Ah I have install a new instance of roundcube with full control. I will let you know how I get on.

**Comment by glennpierce** [comment]
Updating the roundcube code and plugin seemed to solved it. Thanks for the help.
