### ISSUE TITLE
How to search by phone number?

### ISSUE THREAD

**Issue by Katulos** [mstilkerich/carddavclient#31]
Hello.
The server stores contacts in various formats, for example:
`+7 000 000-00-00`
`+70000000000`
What should the search condition look like to find both contacts?

```php
// store +7 000 000-00-00
$item = '+70000000000';
$abook->query(['TEL' => '/'.$item.'/']); // phone not found
//
// store +70000000000
$item = '+7 000 000-00-00';
$abook->query(['TEL' => '/'.$item.'/']); // phone not found
//
// store +70000000000
$item = '+70000000000';
$abook->query(['TEL' => '/'.$item.'/']); // phone found
//
// store +7 000 000-00-00
$item = '+7 000 000-00-00';
$abook->query(['TEL' => '/'.$item.'/']); // phone found
```
Thanks.

**Comment by mstilkerich** [comment]
Hi, unfortunately I think there is nothing you can do here unless you canonically store the phone numbers. CardDav just can do simple plaintext search in the query report. The TEL attribute is a freetext attribute. So if you have numbers in different formats, I don't see a way to do a "semamtic" search that is independent of the format the number is stored in.

**Comment by Katulos** [comment]
I came to the same conclusion.
I'll have to create a contact book synchronization tool with the required phone number format 😭
